# backend/pdf_generator.py
import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Canvas class to generate dynamic page numbers and running footers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        
        # Draw header running text
        self.drawString(54, 750, "PulseKin AI Healthcare Intake - Confidential Summary")
        self.setStrokeColor(colors.HexColor("#cbd5e1"))
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Draw footer
        self.line(54, 55, 558, 55)
        self.drawString(54, 42, "Generated by AppointReady AI. Anonymized patient context schema.")
        self.drawRightString(558, 42, f"Page {self._pageNumber} of {page_count}")
        self.restoreState()

def generate_intake_pdf(session_data, anonymous_id):
    """
    Generates a beautifully styled, clinical-quality intake PDF.
    Returns PDF bytes.
    """
    buffer = io.BytesIO()
    
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=72,
        bottomMargin=72,
        leftMargin=54,
        rightMargin=54
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'IntakeTitle',
        parent=styles['Title'],
        fontSize=22,
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=6,
        fontName="Helvetica-Bold"
    )
    
    subtitle_style = ParagraphStyle(
        'IntakeSubtitle',
        parent=styles['Normal'],
        fontSize=11,
        textColor=colors.HexColor("#64748b"),
        spaceAfter=16,
        fontName="Helvetica"
    )
    
    h1_style = ParagraphStyle(
        'IntakeH1',
        parent=styles['Heading1'],
        fontSize=14,
        textColor=colors.HexColor("#0f172a"),
        spaceBefore=16,
        spaceAfter=8,
        fontName="Helvetica-Bold",
        borderWidth=0,
        borderPadding=0,
        borderColor=colors.HexColor("#3b82f6"),
    )
    
    body_style = ParagraphStyle(
        'IntakeBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor("#334155"),
        spaceAfter=6,
        leading=14,
        fontName="Helvetica"
    )
    
    bullet_style = ParagraphStyle(
        'IntakeBullet',
        parent=body_style,
        leftIndent=20,
        spaceAfter=4,
    )
    
    disclaimer_style = ParagraphStyle(
        'IntakeDisclaimer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor("#94a3b8"),
        spaceBefore=20,
        spaceAfter=4,
        leading=11,
        fontName="Helvetica-Oblique",
        borderWidth=1,
        borderColor=colors.HexColor("#e2e8f0"),
        borderPadding=8,
    )
    
    story = []
    
    # Title
    story.append(Paragraph("AppointReady Intake Summary", title_style))
    story.append(Paragraph(
        f"Patient Code: <b>{anonymous_id}</b> &nbsp;&nbsp;|&nbsp;&nbsp; "
        f"Date: {datetime.now(timezone.utc).strftime('%B %d, %Y at %H:%M UTC')}",
        subtitle_style
    ))
    story.append(Spacer(1, 8))
    
    # Clinical Summary
    story.append(Paragraph("Clinical Summary", h1_style))
    summary = session_data.get("summary", "No summary available.")
    story.append(Paragraph(summary, body_style))
    story.append(Spacer(1, 10))
    
    # Key Metrics Panel
    story.append(Paragraph("Assessment Overview", h1_style))
    specialist = session_data.get("specialist", "General Physician")
    readiness = session_data.get("readiness_score", 50)
    
    panel_data = [
        ["Suggested Specialist", "Readiness Score"],
        [specialist, f"{readiness}%"]
    ]
    panel_table = Table(panel_data, colWidths=[250, 250])
    panel_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f1f5f9")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#475569")),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 10),
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 12),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor("#1e293b")),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ('TOPPADDING', (0,0), (-1,-1), 8),
        ('BOTTOMPADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(panel_table)
    story.append(Spacer(1, 12))
    
    # Recommendations Section
    story.append(Paragraph("Actionable Pre-Consultation Recommendations", h1_style))
    recs = session_data.get("recommendations", [])
    if recs:
        for rec in recs:
            story.append(Paragraph(f"&bull; &nbsp; {rec}", bullet_style))
    else:
        story.append(Paragraph("No custom recommendations available.", bullet_style))
    story.append(Spacer(1, 10))
    
    # Checklist Section
    story.append(Paragraph("Patient Preparation Checklist", h1_style))
    chklist = session_data.get("checklist", [])
    if chklist:
        for chk in chklist:
            story.append(Paragraph(f"[ &nbsp; ] &nbsp; {chk}", bullet_style))
    else:
        story.append(Paragraph("No checklist items generated.", bullet_style))
    story.append(Spacer(1, 15))
    
    # AI Clinical Disclaimer
    disclaimer = (
        "<b>AI Intake Disclaimer:</b> This document is generated by the PulseKin AppointReady clinical intake "
        "assistant based on self-reported patient symptom information. It is designed solely as a conversational preparation "
        "summary for a qualified healthcare professional. It is NOT a clinical diagnosis, medical evaluation, or "
        "treatment recommendation. If the patient is experiencing a medical emergency, acute difficulty breathing, "
        "or sudden chest pain, please instruct them to contact local emergency services immediately."
    )
    story.append(Paragraph(disclaimer, disclaimer_style))
    
    # Build Document
    doc.build(story, canvasmaker=NumberedCanvas)
    
    buffer.seek(0)
    return buffer.getvalue()
